ifeq ($(OS),Windows_NT)
	CHECKOUT_BIN:=bin/goapp/build/checkout.exe
else
	UNAME_S:=$(shell uname -s)
	ifeq ($(UNAME_S),Linux)
		CHECKOUT_BIN:=bin/goapp/build/checkout-linux
	endif
	ifeq ($(UNAME_S),Darwin)
		CHECKOUT_BIN:=bin/goapp/build/checkout-mac
	endif
endif


.PHONY: update
update:
	- @${CHECKOUT_BIN}